import { UserRole } from '@prisma/client';
import { PERMISSIONS, Permission } from './permissions.config';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_APPROVE,
    
    PERMISSIONS.SHOPS_READ,
    PERMISSIONS.SHOPS_UPDATE,
    PERMISSIONS.SHOPS_DELETE,
    PERMISSIONS.SHOPS_APPROVE,
    PERMISSIONS.SHOPS_VERIFY,
    
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.PRODUCTS_APPROVE,
    PERMISSIONS.CATALOG_MANAGE,
    
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_MANAGE,
    
    PERMISSIONS.DRIVERS_READ,
    PERMISSIONS.DRIVERS_UPDATE,
    PERMISSIONS.DRIVERS_APPROVE,
    PERMISSIONS.DRIVERS_LOCATION,
    
    PERMISSIONS.NEGOTIATIONS_READ,
    PERMISSIONS.NEGOTIATIONS_MANAGE,
    
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_MANAGE,
    
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,
    
    PERMISSIONS.PAYOUTS_READ,
    PERMISSIONS.PAYOUTS_APPROVE,
    
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.LOGS_READ,
  ],
  
  [UserRole.SHOPKEEPER]: [
    PERMISSIONS.USERS_READ, // Read own profile
    PERMISSIONS.USERS_WRITE, // Update own profile
    
    PERMISSIONS.SHOPS_CREATE,
    PERMISSIONS.SHOPS_READ,
    PERMISSIONS.SHOPS_UPDATE,
    
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_MANAGE,
    
    PERMISSIONS.PAYOUTS_READ,
    PERMISSIONS.PAYOUTS_REQUEST,
    
    PERMISSIONS.NEGOTIATIONS_READ,
    PERMISSIONS.NEGOTIATIONS_CREATE,
    PERMISSIONS.NEGOTIATIONS_UPDATE,
    
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.SUBSCRIPTIONS_PURCHASE,
    
    PERMISSIONS.REPORTS_CREATE,
  ],
  
  [UserRole.CUSTOMER]: [
    PERMISSIONS.USERS_READ, // Read own profile
    PERMISSIONS.USERS_WRITE, // Update own profile
    
    PERMISSIONS.SHOPS_READ,
    PERMISSIONS.PRODUCTS_READ,
    
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE, // Cancel own order
    
    PERMISSIONS.NEGOTIATIONS_READ,
    PERMISSIONS.NEGOTIATIONS_CREATE,
    PERMISSIONS.NEGOTIATIONS_UPDATE,
    
    PERMISSIONS.REPORTS_CREATE,
  ],
  
  [UserRole.DRIVER]: [
    PERMISSIONS.USERS_READ, // Read own profile
    PERMISSIONS.USERS_WRITE, // Update own profile
    
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_MANAGE, // Update delivery status
    
    PERMISSIONS.DRIVERS_READ, // Read own stats
    PERMISSIONS.DRIVERS_LOCATION,
    
    PERMISSIONS.REPORTS_CREATE,
  ]
};
